[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 main:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = 5000
FLASK_ENV = "production"
DEBUG = "False"
HOST = "0.0.0.0"
CORS_ORIGINS = "*"
